[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "namgpt"
version = "1.0.4"
description = "A beautiful CLI built with Typer, Rich and Questionary"
readme = "README.md"
license = "MIT"
requires-python = ">=3.10"
authors = [
    { name = "Nguyen Nhat Nam" }
]
dependencies = [
    "typer",
    "rich",
    "questionary"
]

[project.scripts]
namgpt = "main:app"